-- Seed Class 6 AI Literacy curriculum (Part 2 PDF) under subjects.slug = 'ai'.
-- Idempotent. Run after 012_ai_program_subject.sql.
-- Source: docs/AICUMEN_Class6_AI_Curriculum 2.pdf

BEGIN;

INSERT INTO content_ingest_batches (source_label, source_file, source_kind, row_count, notes)
VALUES (
  'class6_ai_curriculum_v1',
  'docs/AICUMEN_Class6_AI_Curriculum 2.pdf',
  'manual',
  17,
  'Generated by scripts/generate_grade6_ai_seed.ts — full PROBLEM / Socratic ladder / EXTEND from PDF'
)
ON CONFLICT (source_label) DO UPDATE SET
  row_count = EXCLUDED.row_count,
  ingested_at = NOW();

DO $$
DECLARE
  subj_id INTEGER;
  ch_id INTEGER;
  act_id INTEGER;
  stem_id INTEGER;
BEGIN
  SELECT id INTO subj_id FROM subjects WHERE slug = 'ai';
  IF subj_id IS NULL THEN
    RAISE EXCEPTION 'AI subject not found — run migration 012_ai_program_subject.sql first';
  END IF;

  -- Module 1: What Is AI?
  SELECT c.id INTO ch_id
    FROM chapters c
   WHERE c.subject_id = subj_id AND c.chapter_code = '1';
  IF ch_id IS NULL THEN
    INSERT INTO chapters (subject_id, grade, chapter_code, title, anchor_curriculum, metadata)
    VALUES (
      subj_id, 6, '1', 'What Is AI?',
      'CBSE Class 6 AI Literacy',
      '{"hours":5,"curriculum_pack":"grade6_ai_literacy","blurb":"Machine intelligence vs. human intelligence, AI vs. automation, and the three ways machines learn."}'::jsonb
    ) RETURNING id INTO ch_id;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m1-ai-or-just-a-machine') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m1-ai-or-just-a-machine', 'AI or Just a Machine?', 'quest', 'Class 6 AI',
      1, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M1-01","theme":"Everyday Tech","difficulty":"Developing","stars":1,"emoji":"🤖","accent":"teal","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M1-01', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'Four gadgets are named: a kitchen weighing scale, a UPI app that flags a suspicious payment, a ceiling fan regulator, and a phone camera that recognises faces to unlock. Which of these are AI, and which are simple automation?', NULL,
      '{"answer_type":"short_text","body":{"value":"Automation: the kitchen scale and fan regulator, both follow one fixed rule with no learning involved. AI: the UPI fraud flag and face-unlock camera, both learned a pattern from many past examples."}}'::jsonb,
      '{"run_it":"Hold up (or draw) four cards, one per gadget. Students physically move to an \"AI\" corner or an \"Automation\" corner of the room for each one, then defend their choice.","grade":6}'::jsonb,
      'RUN IT: Hold up (or draw) four cards, one per gadget. Students physically move to an "AI" corner or an "Automation" corner of the room for each one, then defend their choice.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'For each gadget, ask: does it follow one instruction someone wrote in advance, or does it seem to have looked at many examples first?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Look at the kitchen scale and the fan regulator together. What do the two of them have in common in how they work?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'Now look at the UPI fraud flag and the face-unlock camera. What would each of them have needed to see many times before, in order to work at all?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'Ask: could the fan regulator ever become AI? What would have to change? (It would need to learn a pattern, for instance adjusting itself based on how hot the room usually gets at that time of day.)',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m1-sorting-mangoes') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m1-sorting-mangoes', 'Sorting Mangoes with Meera Aunty', 'quest', 'Class 6 AI',
      2, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M1-02","theme":"Kirana / Market","difficulty":"Developing","stars":2,"emoji":"🥭","accent":"amber","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M1-02', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'Meera Aunty has sorted 40 mangoes into "ripe" and "raw" piles, and every mango already has a little sticker saying which pile it belongs to. Her nephew watches all 40, then picks up mango number 41, which has no sticker, and predicts which pile it belongs to. What kind of learning is this?', NULL,
      '{"answer_type":"short_text","body":{"value":"This is supervised learning: the nephew learns from mangoes that already carry the correct label, then applies that pattern to a new, unlabelled case."}}'::jsonb,
      '{"run_it":"Bring (or draw) 10 mango cards, 5 labelled \"ripe\" and 5 labelled \"raw,\" with colour and firmness noted on each. Add one unlabelled card and have students predict its label using the pattern from the first 10.","grade":6}'::jsonb,
      'RUN IT: Bring (or draw) 10 mango cards, 5 labelled "ripe" and 5 labelled "raw," with colour and firmness noted on each. Add one unlabelled card and have students predict its label using the pattern from the first 10.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'What''s the difference between having a labelled example and not having one?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Did the first 40 mangoes already have their correct answer, ripe or raw, written on them?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'So is the nephew guessing mango 41''s label from nothing at all, or from the pattern in 40 labelled examples?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'What would happen if half the stickers were wrong? Would the nephew still learn the right pattern? (This is a gentle first brush with the idea of noisy or incorrect training data.)',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m1-unlabelled-spice-box') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m1-unlabelled-spice-box', 'The Unlabelled Spice Box', 'quest', 'Class 6 AI',
      3, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M1-03","theme":"Kirana / Market","difficulty":"Developing","stars":2,"emoji":"🌶️","accent":"amber","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M1-03', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'A new shop assistant is handed a box with 30 loose spice packets, no labels, all mixed together. He is told to "group the similar ones together" without being told what the groups should be called. He ends up with piles by smell and colour: reddish-orange powders in one pile, dark whole pods in another, pale seeds in a third. What kind of learning does this match?', NULL,
      '{"answer_type":"short_text","body":{"value":"This is unsupervised learning: there are no labels at all, the assistant (or system) finds its own structure by comparing similarities."}}'::jsonb,
      '{"run_it":"Give students a mixed set of 12–15 small objects (buttons, beads, pulses) with no labels and ask them to form their own groups, then explain the rule they used.","grade":6}'::jsonb,
      'RUN IT: Give students a mixed set of 12–15 small objects (buttons, beads, pulses) with no labels and ask them to form their own groups, then explain the rule they used.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Were the spice packets given any names or labels to begin with?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'So how did the assistant decide which pile a packet belonged to, if nobody told him?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'If there''s no correct answer given in advance, and the groups are discovered rather than told, what kind of learning does that sound like?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'Two students given the identical unlabelled box may form different groupings. Discuss: is one of them wrong, or can both groupings be valid?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m1-learning-to-fly-a-kite') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m1-learning-to-fly-a-kite', 'Learning to Fly a Kite', 'quest', 'Class 6 AI',
      4, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M1-04","theme":"Everyday Life","difficulty":"Secure","stars":3,"emoji":"🪁","accent":"sky","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M1-04', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'Aryan has never flown a kite before. Nobody gives him a rulebook. He tries pulling the string a little, the kite dips, he tries pulling harder, it climbs, he keeps adjusting based on what happens each time, and after twenty tries, he can keep the kite steady. Which of the three learning types does this match, and why?', NULL,
      '{"answer_type":"short_text","body":{"value":"This is reinforcement learning: there''s no example data at all, only trial, a consequence (the kite rising or falling), and adjustment toward a goal."}}'::jsonb,
      '{"run_it":"Have a small group play a simple hand-clap rhythm game where a \"reward\" (a point, a clap-back) is given only for a correct pattern, so the group has to adjust their rhythm attempt by attempt.","grade":6}'::jsonb,
      'RUN IT: Have a small group play a simple hand-clap rhythm game where a "reward" (a point, a clap-back) is given only for a correct pattern, so the group has to adjust their rhythm attempt by attempt.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Did anyone hand Aryan a rulebook or a set of correct examples before he started flying the kite?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'What happens right after each pull of the string, does something tell him whether that pull was right or wrong?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'Is that "something" a labelled example, or more like a consequence, the kite rising or dipping, that he adjusts to?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'What is playing the role of the "reward" in Aryan''s kite example? What would happen if the reward (the kite staying up) never came, no matter what he tried?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m1-name-that-learning-type') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m1-name-that-learning-type', 'Name That Learning Type', 'quest', 'Class 6 AI',
      5, 20, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M1-05","theme":"Mixed Review","difficulty":"Secure","stars":3,"emoji":"🎯","accent":"teal","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M1-05', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'Four short scenarios are read aloud: (a) a music app groups songs into "playlists you might like" with no one telling it what the playlists should be, (b) a doctor''s assistant predicts a disease from thousands of past patient records that were each marked with the correct diagnosis, (c) a robot vacuum learns the fastest route around a room only after bumping into furniture many times, (d) an app sorts old family photos into folders by comparing them to a set of pictures you already tagged with names. For each, name the learning type.', NULL,
      '{"answer_type":"short_text","body":{"value":"(a) Unsupervised, groups songs with no given labels. (b) Supervised, learns from records already labelled with the correct diagnosis. (c) Reinforcement, learns by trial, error, and consequence. (d) Supervised, learns from photos you already labelled with names."}}'::jsonb,
      '{"run_it":"Read one scenario at a time. Students hold up one of three cards (Supervised / Unsupervised / Reinforcement) simultaneously, so answers cannot be copied from a neighbour.","grade":6}'::jsonb,
      'RUN IT: Read one scenario at a time. Students hold up one of three cards (Supervised / Unsupervised / Reinforcement) simultaneously, so answers cannot be copied from a neighbour.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'For each scenario, ask first: is there labelled example data given upfront, no labels at all, or just trial-and-error feedback?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'If there are no labels and no reward, but the system is grouping things by similarity, what does that sound like?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'If there IS a reward or consequence driving the behaviour, but no upfront correct-answer examples, what does that sound like instead?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'Ask students to invent one new scenario of their own, from home or their school, for each of the three learning types.',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  -- Module 2: Basic Data Concepts
  SELECT c.id INTO ch_id
    FROM chapters c
   WHERE c.subject_id = subj_id AND c.chapter_code = '2';
  IF ch_id IS NULL THEN
    INSERT INTO chapters (subject_id, grade, chapter_code, title, anchor_curriculum, metadata)
    VALUES (
      subj_id, 6, '2', 'Basic Data Concepts',
      'CBSE Class 6 AI Literacy',
      '{"hours":5,"curriculum_pack":"grade6_ai_literacy","blurb":"Recognising data types, and organising raw information into something a machine, or a mentor, can actually read."}'::jsonb
    ) RETURNING id INTO ch_id;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m2-what-kind-of-data') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m2-what-kind-of-data', 'What Kind of Data Is This?', 'quest', 'Class 6 AI',
      1, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M2-01","theme":"School Life","difficulty":"Developing","stars":1,"emoji":"📊","accent":"sky","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M2-01', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'Four items are shown: the class attendance register, a voice note from the school announcement speaker, a photo of the school Republic Day parade, and a wedding invitation card. Sort each into one of four data types: text, number, image, or sound.', NULL,
      '{"answer_type":"short_text","body":{"value":"Attendance register: mainly numbers (with some text). Announcement voice note: sound. Republic Day photo: image. Wedding card: text."}}'::jsonb,
      '{"run_it":"Bring four real or printed examples into class and have students physically sort them under four labelled headings on a table.","grade":6}'::jsonb,
      'RUN IT: Bring four real or printed examples into class and have students physically sort them under four labelled headings on a table.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Does this item contain written words, numbers, a picture you can see, or something you can only hear?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Look closely at the attendance register, could it actually hold more than one data type at once?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'Sound is different from image, and text is different from number, which of the four fits each remaining item best?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'Can one item hold more than one data type at once? (The attendance register has both text, names, and numbers, roll numbers and present/absent counts.)',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m2-organise-kirana-shelf') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m2-organise-kirana-shelf', 'Organise the Kirana Shelf', 'quest', 'Class 6 AI',
      2, 20, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M2-02","theme":"Kirana / Market","difficulty":"Developing","stars":2,"emoji":"🛒","accent":"amber","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M2-02', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'A shopkeeper has a messy list of 20 items scribbled on paper: rice, soap, toothpaste, dal, shampoo, wheat flour, and so on, with prices written next to each in no particular order. Organise this into a clean table with clear categories (for example, Groceries, Personal Care) and columns for item name and price.', NULL,
      '{"answer_type":"short_text","body":{"value":"A worked example table: categories Groceries and Personal Care, with item name and price columns, alphabetised within each category. Sample: Groceries — Dal (1 kg) 110, Rice (1 kg) 65, Wheat flour (1 kg) 48; Personal Care — Shampoo (small) 90, Soap 35, Toothpaste 55. (Prices simulated for teaching.)"}}'::jsonb,
      '{"run_it":"Give groups the scrambled list on paper strips. They physically arrange the strips into a table on the floor or a large sheet before copying it into a notebook.","grade":6}'::jsonb,
      'RUN IT: Give groups the scrambled list on paper strips. They physically arrange the strips into a table on the floor or a large sheet before copying it into a notebook.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Before organising anything, can you sort the 20 items into just two or three big groups?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Within a group like "Personal Care," is there an order that would make the list easier to scan, like alphabetical?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'What information does each item need next to it to actually be useful, just a name, or a name and a price?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'Once organised, ask: which category has the most items? Which is more expensive on average? Notice how organising data makes new questions answerable that were invisible in the messy list.',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m2-reading-monsoon-chart') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m2-reading-monsoon-chart', 'Reading the Monsoon Chart', 'quest', 'Class 6 AI',
      3, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M2-03","theme":"Weather / Geography","difficulty":"Secure","stars":3,"emoji":"🌧️","accent":"sky","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M2-03', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'A simple bar chart shows rainfall (in mm, simulated figures) for June through September in a small town: June 180, July 310, August 260, September 140. Which month had the heaviest rainfall? How much more rain fell in July than September?', NULL,
      '{"answer_type":"short_text","body":{"value":"Heaviest rainfall: July (310 mm). Difference between July and September: 310 − 140 = 170 mm. (Rainfall figures here are simulated for the exercise, not real recorded data for any specific town.)"}}'::jsonb,
      '{"run_it":"Draw the four bars on the board without numbers first. Have students estimate values purely by comparing bar heights before revealing the numbers.","grade":6}'::jsonb,
      'RUN IT: Draw the four bars on the board without numbers first. Have students estimate values purely by comparing bar heights before revealing the numbers.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Which bar on the chart reaches the highest point?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Now find July''s bar and September''s bar specifically, which one is taller, and by roughly how much?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'To find "how much more" rain fell in one month than another, what do you do with the two numbers, add them or subtract them?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'If a farmer had to pick the single best month to plant a crop that dislikes too much water but needs some rain, which month from this chart looks safest, and why?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m2-build-your-own-data-table') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m2-build-your-own-data-table', 'Build Your Own Data Table', 'quest', 'Class 6 AI',
      4, 20, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M2-04","theme":"Classroom Activity","difficulty":"Developing","stars":2,"emoji":"📋","accent":"teal","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M2-04', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'Each student notes down three things about five classmates: favourite subject, number of siblings, and preferred sport. This is scattered, spoken information. Turn it into a single organised table.', NULL,
      '{"answer_type":"short_text","body":{"value":"Guidance, not a locked answer: No single fixed answer, this activity produces real classroom data. Model the header row (Name / Subject / Siblings / Sport) before students begin, then count occurrences together as a class."}}'::jsonb,
      '{"run_it":"Physical interview activity: students walk around, ask five classmates the three questions, and fill in a blank table template as they go.","grade":6}'::jsonb,
      'RUN IT: Physical interview activity: students walk around, ask five classmates the three questions, and fill in a blank table template as they go.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'What three pieces of information are you collecting from each classmate?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'If those three pieces become your column headers, what should go in the very first column of all?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'Once every row is filled in, how could you find the class''s most common favourite subject just by looking at the finished table?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'Once every student has a table, combine everyone''s tables on the board into one class-wide table. What is the most common favourite subject in the whole class?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  -- Module 3: Pattern Recognition & Decision-Making
  SELECT c.id INTO ch_id
    FROM chapters c
   WHERE c.subject_id = subj_id AND c.chapter_code = '3';
  IF ch_id IS NULL THEN
    INSERT INTO chapters (subject_id, grade, chapter_code, title, anchor_curriculum, metadata)
    VALUES (
      subj_id, 6, '3', 'Pattern Recognition & Decision-Making',
      'CBSE Class 6 AI Literacy',
      '{"hours":5,"curriculum_pack":"grade6_ai_literacy","blurb":"Spotting what repeats, then acting on it, the two-step move every AI system makes, done here entirely by hand."}'::jsonb
    ) RETURNING id INTO ch_id;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m3-dabbawalas-rhythm') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m3-dabbawalas-rhythm', 'The Dabbawala''s Rhythm', 'quest', 'Class 6 AI',
      1, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M3-01","theme":"Mumbai / Logistics","difficulty":"Developing","stars":2,"emoji":"🍱","accent":"amber","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M3-01', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'A dabbawala collects lunchboxes from five buildings in this order every single day: A, C, B, A, C, B, A, C, ? What comes next, and how did you know?', NULL,
      '{"answer_type":"short_text","body":{"value":"The sequence repeats in a fixed 3-step cycle: A, C, B. After ...A, C, B, A, C, the next is B."}}'::jsonb,
      '{"run_it":"Use physical building cards (or students standing in a line) and have the class physically continue the sequence by stepping into the next position.","grade":6}'::jsonb,
      'RUN IT: Use physical building cards (or students standing in a line) and have the class physically continue the sequence by stepping into the next position.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Look at the sequence so far, does anything repeat after a fixed number of steps?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Count how many buildings appear before the pattern starts over. What is that number?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'If the cycle is A, C, B and it has just repeated up to ...A, C, what comes right after C in that cycle?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'If one day the dabbawala had to skip building C because it was closed, what pattern would the delivery sequence show that day?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m3-library-yes-or-no') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m3-library-yes-or-no', 'Should the Library Say Yes or No?', 'quest', 'Class 6 AI',
      2, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M3-02","theme":"School Life","difficulty":"Secure","stars":3,"emoji":"📚","accent":"teal","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M3-02', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'A school library has a simple rule for its digital system: if a book is more than 14 days overdue AND the student has more than 2 books already borrowed, flag the account. Given three students'' records (Student 1: 10 days overdue, 1 book; Student 2: 20 days overdue, 3 books; Student 3: 16 days overdue, 1 book), which accounts get flagged?', NULL,
      '{"answer_type":"short_text","body":{"value":"Only Student 2 is flagged (20 days overdue AND 3 books, both conditions true). Students 1 and 3 each fail at least one condition. This is a rule-based decision, not a learned one, useful for contrasting with AI from Module 1."}}'::jsonb,
      '{"run_it":"Give each group a stack of \"student record\" cards with the two numbers on each, and have them physically sort cards into \"Flag\" and \"No Flag\" piles by applying the rule.","grade":6}'::jsonb,
      'RUN IT: Give each group a stack of "student record" cards with the two numbers on each, and have them physically sort cards into "Flag" and "No Flag" piles by applying the rule.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'What are the two conditions that must BOTH be true for an account to be flagged?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Check Student 1 against both conditions, does either one actually hold true?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'Now check Student 3, they''re well past 14 days overdue, but what about the second condition, the number of books?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'This rule was written by a person, not learned from data. How is this different from an AI system deciding the same thing after studying thousands of past overdue records?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m3-predicting-the-next-over') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m3-predicting-the-next-over', 'Predicting the Next Over', 'quest', 'Class 6 AI',
      3, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M3-03","theme":"Cricket","difficulty":"Extending","stars":4,"emoji":"🏏","accent":"sky","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M3-03', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'In a simulated T20 match, a batter has scored 4, 6, 4, 6, 4 runs off her last five balls faced from one bowler. Based only on this pattern, predict roughly what she might score off the next ball, and explain why a real prediction would need far more data than this.', NULL,
      '{"answer_type":"short_text","body":{"value":"The visible pattern alternates high-low (4, 6, 4, 6, 4), so 6 is a reasonable pattern-based guess, but the real teaching point is that five balls is far too little data, real systems would want the bowler''s full over-by-over history, delivery type, and field placement. (All figures simulated for the exercise.)"}}'::jsonb,
      '{"run_it":"Chart the five scores as dots on a simple number line or bar drawing, then have students mark where they think the sixth dot should sit and defend the choice.","grade":6}'::jsonb,
      'RUN IT: Chart the five scores as dots on a simple number line or bar drawing, then have students mark where they think the sixth dot should sit and defend the choice.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Look at the five scores, do they seem to alternate between two particular numbers?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'If that alternating pattern truly holds, what would come right after ...4, 6, 4?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'Now ask: is five balls really enough data to trust this prediction in a real match? What real information is missing?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'What other information (beyond these five balls) would a real AI system want before making this prediction? List at least three.',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m3-spot-the-odd-one') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m3-spot-the-odd-one', 'Spot the Odd One in the Data', 'quest', 'Class 6 AI',
      4, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M3-04","theme":"Data Detective","difficulty":"Secure","stars":3,"emoji":"🔍","accent":"slate","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M3-04', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'A shop''s daily sales for one week (in rupees, simulated): 2,000 / 2,200 / 1,950 / 2,100 / 15,000 / 2,050 / 2,150. One number does not fit the pattern of the rest. Which one, and what might explain it in real life?', NULL,
      '{"answer_type":"short_text","body":{"value":"Rs. 15,000 is the anomaly, roughly seven times the typical daily figure. Possible explanations: a festival rush day, a bulk order, or a data-entry error, the pattern alone cannot tell us which, only that it needs a closer look. (Figures simulated for the exercise.)"}}'::jsonb,
      '{"run_it":"Plot the seven values as bars on the board (heights roughly to scale), the mismatch becomes visually obvious before any calculation.","grade":6}'::jsonb,
      'RUN IT: Plot the seven values as bars on the board (heights roughly to scale), the mismatch becomes visually obvious before any calculation.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Look at six of the seven numbers, ignoring the one that looks different, are they roughly close to each other?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Which single number breaks that closeness the most?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'In real life, what kind of day could cause one day''s sales to jump far above all the rest?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'An AI fraud-detection system uses exactly this idea, spotting a transaction that does not match a person''s usual pattern. What is one everyday example where you''d want a system to flag something unusual like this?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  -- Module 4: Ethics & Digital Responsibility
  SELECT c.id INTO ch_id
    FROM chapters c
   WHERE c.subject_id = subj_id AND c.chapter_code = '4';
  IF ch_id IS NULL THEN
    INSERT INTO chapters (subject_id, grade, chapter_code, title, anchor_curriculum, metadata)
    VALUES (
      subj_id, 6, '4', 'Ethics & Digital Responsibility',
      'CBSE Class 6 AI Literacy',
      '{"hours":5,"curriculum_pack":"grade6_ai_literacy","blurb":"Privacy, fairness, and safe habits, so a student can use AI and the internet with judgement, not just enthusiasm."}'::jsonb
    ) RETURNING id INTO ch_id;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m4-whose-photo-is-it') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m4-whose-photo-is-it', 'Whose Photo Is It, Really?', 'quest', 'Class 6 AI',
      1, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M4-01","theme":"Digital Footprint","difficulty":"Developing","stars":2,"emoji":"📸","accent":"sky","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M4-01', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'A student posts a photo from a school annual day function online, tagging four classmates by name, without asking them first. Is this a problem? If so, for whom?', NULL,
      '{"answer_type":"short_text","body":{"value":"Discussion points to arrive at together: Consent matters even for photos taken in a shared space; tagging adds to someone else''s digital footprint, not just the poster''s; asking first is a small habit with a real, lasting difference."}}'::jsonb,
      '{"run_it":"Role-play in pairs: one student plays the poster, one plays a tagged classmate who was not asked. Act out the conversation that should have happened before posting.","grade":6}'::jsonb,
      'RUN IT: Role-play in pairs: one student plays the poster, one plays a tagged classmate who was not asked. Act out the conversation that should have happened before posting.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Was anyone in the photo actually asked before it was posted and tagged with their name?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Does tagging someone add information about them to the internet, even though they didn''t post it themselves?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'If a tagged classmate later wanted that photo taken down, could they always make that happen easily and quickly?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'What is a "digital footprint," and how is tagging someone else''s name and face part of building their digital footprint, not just your own?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m4-fair-or-unfair') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m4-fair-or-unfair', 'Fair or Unfair?', 'quest', 'Class 6 AI',
      2, 20, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M4-02","theme":"Bias in AI","difficulty":"Secure","stars":3,"emoji":"⚖️","accent":"amber","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M4-02', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'A school''s new sports-recommendation app only ever suggests cricket to boys and dance to girls, no matter what a student actually enters as their interest. What has gone wrong here, and where would this problem most likely have come from?', NULL,
      '{"answer_type":"short_text","body":{"value":"Discussion points to arrive at together: This is a bias problem, most likely rooted in training data that reflected old assumptions (past enrolment records skewed by gender). The fix starts with better, more varied examples, not just a smarter algorithm."}}'::jsonb,
      '{"run_it":"Small groups design (on paper) what training examples they would feed the app instead, to avoid this exact problem, and present their fix to the class.","grade":6}'::jsonb,
      'RUN IT: Small groups design (on paper) what training examples they would feed the app instead, to avoid this exact problem, and present their fix to the class.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Does the app''s suggestion actually change based on what a student types, or does it seem to depend on something else entirely?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'If this app learned from past examples, like Module 1''s supervised learning, where would those past examples have originally come from?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'If those past examples already reflected old assumptions about who plays what sport, what would the app end up learning to repeat?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'Connect back to Module 1: if this app learned from supervised examples, what does that suggest about the examples it was trained on in the first place?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m4-password-power') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m4-password-power', 'Password Power', 'quest', 'Class 6 AI',
      3, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M4-03","theme":"Online Safety","difficulty":"Developing","stars":1,"emoji":"🔐","accent":"slate","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M4-03', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'Compare four passwords: "123456," "ravi2015" (a birth year), "R@vi!2015#Cricket," and "correcthorsebatterystaple." Rank them from weakest to strongest and explain your ranking.', NULL,
      '{"answer_type":"short_text","body":{"value":"Weakest to strongest, roughly: \"123456\" (an extremely common, guessable sequence), \"ravi2015\" (personal and predictable), \"R@vi!2015#Cricket\" (longer and mixed, but still built from guessable personal details), \"correcthorsebatterystaple\" (long and unpredictable, hard to guess by a pattern-matching attacker)."}}'::jsonb,
      '{"run_it":"Write all four on cards and have students physically arrange them in a line from weakest to strongest, then debate any disagreements.","grade":6}'::jsonb,
      'RUN IT: Write all four on cards and have students physically arrange them in a line from weakest to strongest, then debate any disagreements.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'Which of the four passwords could someone guess just by knowing your name and birth year?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Does adding symbols to a personal detail, like a birth year, make it truly unpredictable, or just longer and fiddlier to type?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'What makes "correcthorsebatterystaple" hard to guess, even though it has no symbols or numbers at all?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'Why might a long, unusual phrase sometimes be just as strong as, or stronger than, a shorter password stuffed with symbols?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM activities WHERE slug = 'ai6-m4-right-to-say-no') THEN
    INSERT INTO activities (
      chapter_id, slug, title, activity_type, source_type_label,
      sort_order, estimated_minutes, ct_skills, ai_concept, status, metadata,
      external_id, chapter_dependent, enrichment_status
    ) VALUES (
      ch_id, 'ai6-m4-right-to-say-no', 'The Right to Say No', 'quest', 'Class 6 AI',
      4, 15, ARRAY['ai_literacy']::text[], NULL, 'published',
      '{"quest_code":"AI6-M4-04","theme":"Privacy / DPDP","difficulty":"Developing","stars":2,"emoji":"🛡️","accent":"teal","source":"AICUMEN_Class6_AI_Curriculum"}'::jsonb,
      'AI6-M4-04', TRUE, 'enriched'
    ) RETURNING id INTO act_id;

    INSERT INTO questions (activity_id, role, sort_order, stem, hint, answer_spec, context, teacher_notes)
    VALUES (
      act_id, 'stem', 0, 'A free learning app asks for permission to access a student''s photo gallery and contact list before letting them start a simple maths quiz. Does the app actually need this information to do its job? What should a student, or a parent, do here?', NULL,
      '{"answer_type":"short_text","body":{"value":"Discussion points to arrive at together: Consent should be tied to what a service actually needs; unrelated permission requests are a signal to pause and ask why; it is reasonable, and encouraged, to say no or check with an adult first."}}'::jsonb,
      '{"run_it":"Have students list, for three apps they actually use, what permission each one asks for versus what it actually needs to do its stated job.","grade":6}'::jsonb,
      'RUN IT: Have students list, for three apps they actually use, what permission each one asks for versus what it actually needs to do its stated job.'
    ) RETURNING id INTO stem_id;

    INSERT INTO questions (activity_id, role, sort_order, label, stem, teacher_notes)
    VALUES
      (act_id, 'coach_step', 1, 'Clue 1', 'What does a simple maths quiz actually need to know about you in order to function?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 2, 'Clue 2', 'Does "photo gallery" or "contact list" appear anywhere in that list of real needs?', 'Reveal one clue per student attempt.'),
      (act_id, 'coach_step', 3, 'Clue 3', 'India''s DPDP Act says consent should be specific and informed, not a single blanket click. What does an unrelated permission request suggest about that standard?', 'Reveal one clue per student attempt.');

    INSERT INTO questions (activity_id, parent_question_id, role, sort_order, stem, answer_spec)
    VALUES (
      act_id, stem_id, 'extend', 4, 'India''s DPDP Act 2023 gives individuals a right to meaningful consent, permission that is specific and informed, not just a single blanket "Accept All" click. Why does a maths-quiz app asking for contacts fail that standard?',
      '{"answer_type":"open_rubric","body":{"rubric":["Reasoned discussion; answers may vary."]}}'::jsonb
    );
  END IF;

END $$;

COMMIT;
